### ISSUE TITLE
Mackie buzzing

### ISSUE THREAD

**Issue by Muirrum** [WPI-LNL/td#26]
Both the fader Mackie and one of the encoder mackies have buzzing and hissing on their outputs.

**Comment by mjhaahr** [comment]
It's probably power supply issues (which will be a pain to check and repair). But I also need to check if the contact cleaner helped.

**Comment by mjhaahr** [comment]
1402-VLZ and 1202-VLZ

**Comment by mjhaahr** [comment]
Potentiometer Mackie seems to be fine?
