### ISSUE TITLE
Freedom Par Screen not turning on (asset tag: U01250)

### ISSUE THREAD

**Issue by salochinYom** [WPI-LNL/td#30]
turned on freedom par and screen did not come on.
no blinking dots,  tried pressing all other buttons.

battery indicator lights work,
still receives D-Fi,
lights still work.

-Nicholas Moy

**Comment by Muirrum** [comment]
RMA #29

**Comment by mjhaahr** [comment]
Emailed Bob Hatch #29

**Comment by mjhaahr** [comment]
Service request filed with Chauvet, they should be under warranty #29
