### ISSUE TITLE
Digico Not receiving Dante channels correctly /macbook not transimitting correctly.

### ISSUE THREAD

**Issue by salochinYom** [WPI-LNL/td#36]
![20221218_190607](https://user-images.githubusercontent.com/73899470/208776728-376ea7e9-1959-40c2-80f0-246e3a87b0ae.jpg)
![20221218_190538](https://user-images.githubusercontent.com/73899470/208776733-afdd786e-631c-4aaf-8f10-9dd78bd99b59.jpg)
on a dante network consisting of the Digico s31, Mac 1, UXLD, Tio1608-d, and the network rack the macbook was not transmitting to the inputs specfifed in dante controller. when removing the MacBook and the digico from the network and replacing it with the m32, the audio seemed to work fine.

**Comment by mjhaahr** [comment]
Dante was le wrecked, so assume closed
