### ISSUE TITLE
122 XLR cable stuck

### ISSUE THREAD

**Issue by Amanhire** [WPI-LNL/td#39]
Quickly looked at. Spring on XLR port not engaging

**Comment by Amanhire** [comment]
![Image](https://user-images.githubusercontent.com/43322169/215945357-5da15466-89ee-4973-b2ee-275261fc9778.jpg)

**Comment by mjhaahr** [comment]
I poked at it, it's definitely stuck, the tab on the port broke, replace the port

**Comment by Amanhire** [comment]
Removed XLR port, returned to service for now, ordered new part
