### ISSUE TITLE
Fader Mackie is sad

### ISSUE THREAD

**Issue by mjhaahr** [WPI-LNL/td#4]
Needs some contact cleaner

**Comment by Amanhire** [comment]
not sure if this ever got fixed. can you check it out @HVATK

**Comment by mjhaahr** [comment]
I contact cleaned some of the channels (should be first 4)

**Comment by HVATK** [comment]
Re-contact cleaned last week, all faders now work, except for #3, which is still completely sad. You can have sound or no sound on that fader, but not much inbetween.

**Comment by Amanhire** [comment]
Tried at an "event". completely borked. EOL. trash. bye
