### ISSUE TITLE
RF Cascade for ULXD

### ISSUE THREAD

**Issue by mjhaahr** [WPI-LNL/td#44]
- Look at ULXD to figure out if BNC is isolated
- Look if I/O Panel has two more Outs (if not, by new panel)

**Comment by benjamin-antupit** [comment]
> - Look at ULXD to figure out if BNC is isolated

ULXD Receiver has BNC cascade out for antennas A and B. 

> - Look if I/O Panel has two more Outs (if not, by new panel)

I/O panel has more than 2 cutouts unpopulated.

**Comment by mjhaahr** [comment]
> ULXD Receiver has BNC cascade out for antennas A and B.

That's not what I meant and you know it, I'm talking of the connectors are grounded or not

**Comment by Amanhire** [comment]
https://www.mouser.com/ProductDetail/Neutrik/NBB75DFIB?qs=%252BrH4t%252BeVZ2OaW3zrRqAaDQ%3D%3D

**Comment by mjhaahr** [comment]
Maybe use Neutrik DSS Labels (one [red](https://www.mouser.com/ProductDetail/Neutrik/DSS-RED?qs=jCymNF74TgUAzt8gDJqw5Q%3D%3D) and one [blue](https://www.mouser.com/ProductDetail/Neutrik/DSS-BLUE?qs=jCymNF74TgXM2RVfAn7KZQ%3D%3D)) for Antenna cascade and labeling

Use the green BNC shorts (or the even shorter ones in the TD tool bench)
