### ISSUE TITLE
SM58s XLR stuck

### ISSUE THREAD

**Issue by Amanhire** [WPI-LNL/td#72]

**Comment by HVATK** [comment]
Fixed, pushed XLR back in, tightened set screw. Returned to mic bin 1 and removed TF tape. Also checked the SM58 on the desk, figured it had a similar issue, but it seemed fine, also sent it back to bin 1. Went ahead and re-organized all 3 mic bins while I was at it, everything is now in the right spot per the manifests on the lids. Things not on manifests are living with similar mics (ie no more instrument mics living in the bin full of vocal mics).
